/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfms;

import java.awt.Color;
import java.time.format.DateTimeFormatter;

import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOUSE OF PRAYER
 */


public class Account_Create extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    PreparedStatement pst;
    
    
    public Account_Create() {
        setUndecorated(true);
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        DateTimeFormatter format = DateTimeFormatter.ofPattern("HH:mm");
        initComponents();
        
        uiDate.setText((java.time.LocalDate.now()).toString());
        uiTime.setText(format.format(java.time.LocalTime.now()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexButtonGroup = new javax.swing.ButtonGroup();
        backgroundPanel = new RoundedPanel(50);
        mainPanel = new RoundedPanel(50);
        uiDate = new javax.swing.JLabel();
        uiTime = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        signupLink = new javax.swing.JLabel();
        usernameTextBox = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        pswIcon = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pswTextLabel = new javax.swing.JLabel();
        passwordTextBox = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        usignupLink = new javax.swing.JLabel();
        loginHeaderText = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        loginHeaderText1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        nameTextBox = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        emailTextBox = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        phoneNumberTextBox = new javax.swing.JTextField();
        birthdayTextBox = new com.toedter.calendar.JDateChooser();
        femaleRadioButton = new javax.swing.JRadioButton();
        maleRadioButton = new javax.swing.JRadioButton();
        alertText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(900, 50));
        setMaximumSize(new java.awt.Dimension(1242, 2688));
        setPreferredSize(new java.awt.Dimension(350, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        backgroundPanel.setBackground(new java.awt.Color(255, 153, 0));
        backgroundPanel.setOpaque(false);
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uiDate.setText("Date");
        mainPanel.add(uiDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        uiTime.setText("Time");
        mainPanel.add(uiTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        mainPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 30));

        signupLink.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        signupLink.setText("LOG IN");
        signupLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLinkMouseClicked(evt);
            }
        });
        mainPanel.add(signupLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 40, -1, -1));

        usernameTextBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usernameTextBox.setForeground(new java.awt.Color(92, 84, 107));
        usernameTextBox.setText("Username");
        usernameTextBox.setAutoscrolls(false);
        usernameTextBox.setBorder(null);
        usernameTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTextBox.setOpaque(false);
        usernameTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextBoxFocusGained(evt);
            }
        });
        mainPanel.add(usernameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 250, 40));

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        loginButton.setText("SIGN UP");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        mainPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 250, 40));

        pswIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Password.png"))); // NOI18N
        mainPanel.add(pswIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Avater.png"))); // NOI18N
        mainPanel.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 330, -1, -1));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 250, -1));
        mainPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 250, -1));

        pswTextLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pswTextLabel.setForeground(new java.awt.Color(92, 84, 107));
        pswTextLabel.setText("Password");
        mainPanel.add(pswTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, -1));

        passwordTextBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        passwordTextBox.setForeground(new java.awt.Color(92, 84, 107));
        passwordTextBox.setBorder(null);
        passwordTextBox.setOpaque(false);
        passwordTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextBoxFocusGained(evt);
            }
        });
        passwordTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextBoxActionPerformed(evt);
            }
        });
        mainPanel.add(passwordTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setText("Already have an account ?");
        mainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 170, -1));

        usignupLink.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        usignupLink.setForeground(new java.awt.Color(92, 84, 107));
        usignupLink.setText("<html> <body>  <u>log In</u>  </body> </html> ");
        usignupLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usignupLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usignupLinkMouseClicked(evt);
            }
        });
        mainPanel.add(usignupLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, -1, -1));

        loginHeaderText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginHeaderText.setForeground(new java.awt.Color(92, 84, 107));
        loginHeaderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHeaderText.setText("account");
        mainPanel.add(loginHeaderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 40));

        backButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back.png"))); // NOI18N
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        mainPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, -1, -1));

        loginHeaderText1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginHeaderText1.setForeground(new java.awt.Color(92, 84, 107));
        loginHeaderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHeaderText1.setText("Create your\n");
        mainPanel.add(loginHeaderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Name.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Email.png"))); // NOI18N
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Calender.png"))); // NOI18N
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Phone.png"))); // NOI18N
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        mainPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, -1));

        nameTextBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameTextBox.setForeground(new java.awt.Color(92, 84, 107));
        nameTextBox.setText("Your name");
        nameTextBox.setAutoscrolls(false);
        nameTextBox.setBorder(null);
        nameTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextBox.setOpaque(false);
        nameTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextBoxFocusGained(evt);
            }
        });
        mainPanel.add(nameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 250, 40));
        mainPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 250, -1));

        emailTextBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        emailTextBox.setForeground(new java.awt.Color(92, 84, 107));
        emailTextBox.setText("Email");
        emailTextBox.setAutoscrolls(false);
        emailTextBox.setBorder(null);
        emailTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextBox.setOpaque(false);
        emailTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextBoxFocusGained(evt);
            }
        });
        mainPanel.add(emailTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 40));
        mainPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 247, -1));
        jSeparator5.getAccessibleContext().setAccessibleName("");

        phoneNumberTextBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        phoneNumberTextBox.setForeground(new java.awt.Color(92, 84, 107));
        phoneNumberTextBox.setText("Phone number");
        phoneNumberTextBox.setAutoscrolls(false);
        phoneNumberTextBox.setBorder(null);
        phoneNumberTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phoneNumberTextBox.setOpaque(false);
        phoneNumberTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberTextBoxFocusGained(evt);
            }
        });
        mainPanel.add(phoneNumberTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 250, 40));
        mainPanel.add(birthdayTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 250, 30));

        sexButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        femaleRadioButton.setForeground(new java.awt.Color(92, 84, 107));
        femaleRadioButton.setText("FEMALE");
        femaleRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        sexButtonGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        maleRadioButton.setForeground(new java.awt.Color(92, 84, 107));
        maleRadioButton.setText("MALE");
        maleRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        alertText.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        alertText.setForeground(new java.awt.Color(255, 51, 0));
        alertText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPanel.add(alertText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 250, -1));

        backgroundPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 344, 645));
        mainPanel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private void passwordTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordTextBoxActionPerformed

    private void signupLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLinkMouseClicked
        // TODO add your handling code here:
        new Account_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupLinkMouseClicked

    private void nameTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextBoxFocusGained
        // TODO add your handling code here:
        nameTextBox.setText("");
    }//GEN-LAST:event_nameTextBoxFocusGained

    private void emailTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextBoxFocusGained
        // TODO add your handling code here:
        emailTextBox.setText("");
    }//GEN-LAST:event_emailTextBoxFocusGained

    private void phoneNumberTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberTextBoxFocusGained
        // TODO add your handling code here:
        phoneNumberTextBox.setText("");
    }//GEN-LAST:event_phoneNumberTextBoxFocusGained

    private void usernameTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextBoxFocusGained
        // TODO add your handling code here:
        usernameTextBox.setText("");
    }//GEN-LAST:event_usernameTextBoxFocusGained

    private void passwordTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextBoxFocusGained
        // TODO add your handling code here:
        pswTextLabel.setText("");
    }//GEN-LAST:event_passwordTextBoxFocusGained

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        alertText.setText("");
        
        String sex;
        ButtonModel maleRadioButtonM = maleRadioButton.getModel();
        
        
        System.out.println(birthdayTextBox.getDate());
        System.out.println();
        try{
                 int amount=Integer.parseInt(passwordTextBox.getText());
        
        if(nameTextBox.getText().equals("")||nameTextBox.getText().equals("Your name")||emailTextBox.getText().equals("")||emailTextBox.getText().equals("Email")||phoneNumberTextBox.getText().equals("")||phoneNumberTextBox.getText().equals("Phone number")
         || usernameTextBox.getText().equals("")||usernameTextBox.getText().equals("username") || passwordTextBox.getText().equals("") ||birthdayTextBox.getDate()==null||sexButtonGroup.getSelection()==null)  
           {alertText.setText("*Input error please check inputs");}
        else if( emailTextBox.getText().length()<10){
            JOptionPane.showMessageDialog(null, "Email error");
        }

        else {
            
            if(sexButtonGroup.getSelection().equals(maleRadioButtonM)){  sex="M";  }
            else{ sex="F"; }
            
        
               String sql="SELECT * FROM user_account WHERE Username=? or PhoneNumber=? ";
                try(Connection con=Sql.getConnection();){
                pst=con.prepareStatement(sql);
                pst.setString(1, usernameTextBox.getText());
                pst.setString(2, phoneNumberTextBox.getText());
               try (ResultSet results = pst.executeQuery()) {
                      if (results.next()) {
                       alertText.setText("*Username or phone number already exist"); }
                      else{   
                       sql ="INSERT into user_account (Name, Email, PhoneNumber, Sex, Birthday, Username, Password)"
                         + "  values(?,?,?,?,?,?,?)";
            
                                  try (Connection con1=Sql.getConnection()){
                                      
                                  System.out.println("SQL:Connected");
                                  
                                  
                                  New_Account newAccount =  new New_Account(nameTextBox.getText(),usernameTextBox.getText(),birthdayTextBox.getDate().toString(),
                                  sex,emailTextBox.getText(),passwordTextBox.getText(),phoneNumberTextBox.getText());

                                  pst=con1.prepareStatement(sql);
                                  pst.setString(1, newAccount.getName());
                                  pst.setString(2, newAccount.getEmail());
                                  
                                  pst.setString(3, newAccount.getPhoneNuber());
                                  pst.setString(4, newAccount.getSex());
                                  pst.setString(5, newAccount.getbirthday());
                                  pst.setString(6, newAccount.getUserName());
                                  pst.setString(7, newAccount.getPassword());

                                  
                                  pst.execute();
                                  System.out.println("sucess");
                                   new Account_LogIn().setVisible(true);
                                    this.dispose();
                                   }

                                  catch(SQLException ex){
                                // JOptionPane.showMessageDialog(null, ex);
                                  System.out.println("Error:Unable to connect & Insert Data");
                                  JOptionPane.showMessageDialog(null, "check phonenumber");

                              }
        }
                            } catch (SQLException ex) {
                                 Logger.getLogger(Account_Create.class.getName()).log(Level.SEVERE, null, ex);
                                 System.out.println(ex);
                }
                } catch (SQLException ex) {
                Logger.getLogger(Account_Create.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
                
        }
        }
        catch(java.lang.NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "check phonenumber");
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        new Account_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void usignupLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usignupLinkMouseClicked
        // TODO add your handling code here:
         new Account_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usignupLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account_Create().setVisible(true);
                 
            }
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertText;
    private javax.swing.JLabel backButton;
    private javax.swing.JPanel backgroundPanel;
    private com.toedter.calendar.JDateChooser birthdayTextBox;
    private javax.swing.JTextField emailTextBox;
    private javax.swing.JLabel exitButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginHeaderText;
    private javax.swing.JLabel loginHeaderText1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField nameTextBox;
    private javax.swing.JPasswordField passwordTextBox;
    private javax.swing.JTextField phoneNumberTextBox;
    private javax.swing.JLabel pswIcon;
    private javax.swing.JLabel pswTextLabel;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.JLabel signupLink;
    private javax.swing.JLabel uiDate;
    private javax.swing.JLabel uiTime;
    private javax.swing.JLabel userIcon;
    private javax.swing.JTextField usernameTextBox;
    private javax.swing.JLabel usignupLink;
    // End of variables declaration//GEN-END:variables
}
